#syntax=docker/dockerfile:1.2

FROM  eicweb.phy.anl.gov:4567/containers/eic_container/eic:@EIC_TAG@

LABEL maintainer="Whitney Armstrong <warmstrong@anl.gov>" \
      name="juggler" \
      group="EIC/juggler" \
      march="native" \
      basedist="debian" \
      base="eic_container/eic"

RUN cd /tmp             \
      && export CLICOLOR_FORCE=1 \
      && git clone  https://eicweb.phy.anl.gov/EIC/NPDet.git \
      && mkdir -p NPDet/build && cd NPDet/build \
      && cmake ../. -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/usr/local \
      && make -j30  && make -j4 install \
      && cd /tmp && rm -rf /tmp/NPDet 

RUN cd /tmp             \
      && export CLICOLOR_FORCE=1 \
      && git clone -b @EIC_DATA_MODEL_VERSION@ https://eicweb.phy.anl.gov/EIC/eicd.git \
      && mkdir -p eicd/build && cd eicd/build \
      && cmake ../. -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/usr/local \
      && make -j30  && make -j4 install \
      && cd /tmp && rm -rf /tmp/eicd 

RUN cd /tmp             \
      && export CLICOLOR_FORCE=1 \
      && git clone  -b @JUGGLER_BRANCH@ https://eicweb.phy.anl.gov/EIC/juggler.git \
      && mkdir -p juggler/build && cd juggler/build \
      && cmake ../. -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/usr/local \
      && make -j30  && make -j4 install \
      && cd /tmp && rm -rf /tmp/juggler 

